# Generated by Django 5.1.6 on 2025-04-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_schedule_ticket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Events',
        ),
    ]
