# Generated by Django 5.1.6 on 2025-04-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_event_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
