# Generated by Django 5.1.6 on 2025-04-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_orderticket_attendee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderticket',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
