# Generated by Django 5.1.6 on 2025-04-30 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_orderticket_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderticket',
            name='qty',
        ),
        migrations.AddField(
            model_name='orderticket',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.ticket'),
        ),
    ]
