# Generated by Django 5.1.6 on 2025-05-02 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_ticket_type_ticket_name_delete_tickettype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.orderticket'),
        ),
    ]
