# Generated by Django 5.1.6 on 2025-05-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_attendee_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderticket',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderticket',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Attendee',
        ),
    ]
