# Generated by Django 5.1.6 on 2025-05-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_orderticket_event_alter_orderticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderticket',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
