# Generated by Django 5.2 on 2025-06-17 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_orderticket_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='name',
            new_name='event_name',
        ),
    ]
